#! /bin/sh

### BEGIN INIT INFO
# Provides:          jia-l
# Description:       control starling for cradle applications
### END INIT INFO

# Author: jia-l <jia-l@is.naist.jp>
# Do NOT "set -e"
PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin
SCRIPTNAME=starling_init_script_for_cradle


NAME=starling
DAEMON="/usr/bin/$NAME"

LISTEN=127.0.0.1
PORT=15151
SPOOLDIR=/var/spool/starling
PIDFILE=/var/run/starling/starling.pid
LOGFILE=/var/log/starling/starling.log
OPTS="-h $LISTEN -p $PORT -d -q $SPOOLDIR -P $PIDFILE -L $LOGFILE"

[ -x "$DAEMON" ] || exit 0

do_start() {
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $OPTS
}

do_stop() {
	start-stop-daemon --stop --quiet --pidfile $PIDFILE
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart)
	do_stop
	sleep 2
	do_start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac