#! /bin/sh

### BEGIN INIT INFO
# Provides:          jia-l
# Description:       control workling for cradle applications
### END INIT INFO

# Author: jia-l <jia-l@is.naist.jp>
# Do NOT "set -e"
PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin
SCRIPTNAME=workling_init_script_for_cradle

NAME=workling_client

DAEMON="/home/jia-l/rails/cradle/current/script/$NAME"
PIDFILE_1=/home/jia-l/rails/cradle/current/log/workling-client-1.pid
PIDFILE_2=/home/jia-l/rails/cradle/current/log/workling-client-2.pid
PIDFILE_3=/home/jia-l/rails/cradle/current/log/workling-client-3.pid

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0


do_start()
{
	if [ ! -e "$PIDFILE_1" ]
	then
		sudo -u jia-l RAILS_ENV=production $DAEMON --number 1 start
	fi

	if [ ! -e "$PIDFILE_2" ]
	then
		sudo -u jia-l RAILS_ENV=production $DAEMON --number 2 start
	fi

	if [ ! -e "$PIDFILE_3" ]
	then
		sudo -u jia-l RAILS_ENV=production $DAEMON --number 3 start
	fi
}

do_stop()
{
	sudo -u jia-l RAILS_ENV=production $DAEMON --number 1 stop
	sudo -u jia-l RAILS_ENV=production $DAEMON --number 2 stop
	sudo -u jia-l RAILS_ENV=production $DAEMON --number 3 stop
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart)
	do_stop
	sleep 2
	do_start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac