#! /bin/sh

### BEGIN INIT INFO
# Provides:          jia-l
# Description:       control workling for cradle applications
### END INIT INFO

# Author: jia-l <jia-l@is.naist.jp>
# Do NOT "set -e"
PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin
SCRIPTNAME=workling_init_script_for_cradle

NAME=workling_client

DAEMON_1="/home/jia-l/rails/cradle/current/script/$NAME"
PIDFILE_1=/home/jia-l/rails/cradle/current/log/cradle-workling.pid

DAEMON_2="/home/jia-l/rails/seinan/current/script/$NAME"
PIDFILE_2=/home/jia-l/rails/seinan/current/log/seinan-workling.pid

# Exit if the package is not installed
[ -x "$DAEMON_1" ] || exit 0
[ -x "$DAEMON_2" ] || exit 0


do_start()
{
	if [ ! -e "$PIDFILE_1" ]
	then
		sudo -u jia-l RAILS_ENV=production $DAEMON_1 start
	fi

	if [ ! -e "$PIDFILE_2" ]
	then
		sudo -u jia-l RAILS_ENV=production $DAEMON_2 start
	fi
}

do_stop()
{
	sudo -u jia-l RAILS_ENV=production $DAEMON_1 stop
	sudo -u jia-l RAILS_ENV=production $DAEMON_2 stop
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart)
	do_stop
	sleep 2
	do_start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac