#! /bin/bash

### BEGIN INIT INFO
# Provides:          jia-l
# Description:       control workling for cradle applications
### END INIT INFO

# Author: jia-l <jia-l@is.naist.jp>
# Do NOT "set -e"
PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin
SCRIPTNAME=workling_init_script_for_cradle


temp_dirs=(`ls /home/jia-l/rails`)
declare -a DIRS
declare -a PIDFILES
declare -a DAEMONS
len=${#temp_dirs[*]}
i=0
while [ $i -lt $len ]; do
    if [ -x "/home/jia-l/rails/${temp_dirs[$i]}/current/script/workling_client" ]; then
        DAEMONS[$i]="/home/jia-l/rails/${temp_dirs[$i]}/current/script/workling_client"
        DIRS[$i]=${temp_dirs[$i]}
        PIDFILES[$i]="/home/jia-l/rails/${temp_dirs[$i]}/current/log/workling-client-${temp_dirs[$i]}.pid"
    fi
    let i++
done

do_start()
{
    len=${#DIRS[*]}
    i=0
    while [ $i -lt $len ]; do
        if [ ! -e "${PIDFILES[$i]}" ]; then
            sudo -u jia-l RAILS_ENV=production ${DAEMONS[$i]} --name ${DIRS[$i]} start
        fi
        let i++
    done
}

do_stop()
{
    len=${#DIRS[*]}
    i=0
    while [ $i -lt $len ]; do
        sudo -u jia-l RAILS_ENV=production ${DAEMONS[$i]} --name ${DIRS[$i]} stop
        let i++
    done
}

case "$1" in
  start)
do_start
;;
  stop)
do_stop
;;
  restart)
do_stop
sleep 2
do_start
;;
  *)
  echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
  exit 3
  ;;
esac