#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'
require 'yaml'

number = 0 
for i in 0..ARGV.length 
  if ARGV[i] == '--number' 
    number = ARGV[i + 1] 
    2.times {ARGV.delete_at(i)} 
  end 
end

puts "Workling Number: #{number}"

options = {
  :app_name   => "workling-client-#{number}",
  :ARGV       => ARGV,
  :dir_mode   => :normal,
  :dir        => File.join(File.dirname(__FILE__), '..', 'log'),
  :log_output => true,
  :multiple   => false,
  :backtrace  => true,
  :monitor    => true
}

workling = File.join(File.dirname(__FILE__), '..', 'vendor', 'plugins', 'workling', 'script', 'listen.rb')

Daemons.run(workling, options)